# Generated by Django 3.2.9 on 2021-11-05 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='negative_votes',
            field=models.IntegerField(default=0),
        ),
    ]
